In [1]:
import numpy as np

In [ ]:
a = [1,2,4,6,2,1,3]
for i in a:
  for j in a:
    if


Basic Python

In [ ]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


Numbers

In [ ]:
x = 4
print (x, type(x))

4 <class 'int'>


In [ ]:
print(x +1 )
print(x -1 )
print(x *2 )
print( x ** 2)


5
3
8
16


In [ ]:
x += 1
print(x)
x *= 2
print(x)

5
10


In [ ]:
y = 2.5
print(type(y))
print(y, y+1, y*2, y** 2)

<class 'float'>
2.5 3.5 5.0 6.25


Booleans

In [ ]:
t,f = True, False
print(type(t))

<class 'bool'>


In [ ]:
print(t and f)
print(t or f)
print (not t)
print (t != f)

False
True
False
True


Strings


In [ ]:
hello = 'hello'
world = 'world'
print(hello, len(hello))

hello 5


In [ ]:
hw = hello + ' ' + world
print(hw)

hello world


In [ ]:
hw12 = '%s %s %d' %(hello, world, 12)
print(hw12)

hello world 12


Strings method

In [ ]:
s = 'hello'
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))

print('  world  '.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


Containers

List

In [ ]:
xs = [3,1,2]
print(xs, xs[2])
print(xs[-1])

[3, 1, 2] 2
2


In [ ]:
xs[2] = 'foo'
print(xs)

[3, 1, 'foo']


In [ ]:
xs.append('bar')
print(xs)

[3, 1, 'foo', 'bar']


In [ ]:
x = xs.pop()
print(x,xs)

bar [3, 1, 'foo']


Slicing

In [ ]:
nums = [0,1,2,3,4]
# nums = range(5)
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[-1])
print(nums, type(nums))

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
4
[0, 1, 2, 3, 4] <class 'list'>


In [ ]:
nums = range(5)    # range is a built-in function that creates a list of integers
print( nums)         # Prints "[0, 1, 2, 3, 4]"
print (nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print (nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print (nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print (nums[:] )     # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print (nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
# nums[2:4] = [8, 9] # Assign a new sublist to a slice
print (nums, type(nums) )

range(0, 5)
range(2, 4)
range(2, 5)
range(0, 2)
range(0, 5)
range(0, 4)
range(0, 5) <class 'range'>


Loops

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
  print(animal)

cat
dog
monkey


In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
  print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


List comprehensions

In [ ]:
nums = [0,1,2,3,4]
squares = []
for x in nums:
  squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
nums = [0,1,2,3,4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


In [ ]:
nums = [0,1,2,3,4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)


[0, 4, 16]


Dictionaries

In [ ]:
d = {'cat': 'cute', 'dog' : 'furry'}
print(d['cat'])
print('cat' in d)

cute
True


In [ ]:
d['fish'] = 'wet'
print(d['fish'])

wet


In [ ]:
print(d['monkey'])

KeyError: ignored

In [ ]:
print(d.get('monkey', 'N/A'))
print(d.get('fish', 'N/A'))

N/A
wet


In [ ]:
del(d['fish'])
print(d.get('fish', 'N/A'))

N/A


In [ ]:
d = {'person' : 2, 'cat': 4 , 'spider': 8}
for animal in d:
  legs = d[animal]
  print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [ ]:
nums = [0,1,2,3,4]
even_num_to_square = {x: x ** 2 for x in nums if x %2 ==0}
print(even_num_to_square)


{0: 0, 2: 4, 4: 16}


Sets

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)
print('fish' in animals)

True
False


In [ ]:
animals.add('fish')
print('fish' in animals)
print(len(animals))

True
3


In [ ]:
animals.add('cat')
print (len(animals))
animals.remove('cat')
print(len(animals))

3
2


In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
  print('#%d : %s' % (idx + 1, animal))

#1 : dog
#2 : fish
#3 : cat


In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


Tuples

In [ ]:
d = {(x, x + 1): x for x in range(10)}
t = (5,6)
print(type(t))
print(d[t])
print(d[(1,2)])

<class 'tuple'>
5
1


In [ ]:
t[0]

5

Functions

In [ ]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negative'
  else:
    return 'zero'

for x in [-1, 0, 1]:
  print (sign(x))


negative
zero
positive


In [ ]:
def hello(name, loud = False):
  if loud:
    print('HELLO, %s' % name.upper())
  else:
    print('Hello, %s' % name)

hello('Bob')
hello('Fred', loud = True)

Hello, Bob
HELLO, FRED


Classes

In [ ]:
class Greeter:
  def __init__(self, name):
    self.name = name

  def greet(self, loud = False):
    if loud :
      print('HELLO, %s' % self.name.upper())
    else:
      print('Hello, %s' % self.name)

g = Greeter('Fred')
g.greet()
g.greet(loud = True)

Hello, Fred
HELLO, FRED


Numpy

In [4]:
import numpy as np

In [9]:
a = np.array([1,2,14,5,7,8,9,4])
np.median(a)

6.0

In [8]:
b = np.sort(a)
b


array([ 1,  2,  4,  5,  7,  8,  9, 14])

Arrays

In [ ]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
b = np.ones((1,2))
b

array([[1., 1.]])

In [ ]:
c = np.full((2,2), 7)
c

array([[7, 7],
       [7, 7]])

In [ ]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [ ]:
e = np.random.random((2,2))
e

array([[0.5767603 , 0.5420523 ],
       [0.66843838, 0.45327792]])

Array indexing

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a = [1,2,5,7,4,6,2,3]
for i in range(len(a)):
  for j in range(i +1, len(a)):
    if a[i] >= a[j]:
      tg = a[i]
      a[i] = a[j]
      a[j] = tg

a

[1, 2, 2, 3, 4, 5, 6, 7]

In [ ]:
c = (a>5)
c

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
b


array([[2, 3],
       [6, 7]])

In [ ]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])

2
77


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a= np.array([[1,2], [3,4], [5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))

[1 4 5]
[1 4 5]


In [ ]:
print(a[[0,0], [1,1]])
print(np.array(a[0,1], a[0,1]))

[2 2]
2


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])